### ISSUE TITLE
ComicInfoXml should be ComicInfo & can't import in kavita

### ISSUE THREAD

**Issue by ziweiwai** [9-FS/nhentai_archivist#51]
Hey,

I was trying to import some downloads into kavita as a test since komga is very slow with my library. However, it was throwing a ton of xml deserialization errors like so

```
System.InvalidOperationException: There is an error in XML document (0, 0).
 ---> System.InvalidOperationException: <ComicInfoXml xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderComicInfo.Read3_ComicInfo()
   at InvokeStub_XmlSerializationReaderComicInfo.Read3_ComicInfo(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at API.Services.ArchiveService.Deserialize(Stream stream) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\ArchiveService.cs:line 501
   at API.Services.ArchiveService.GetComicInfo(String archivePath) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\ArchiveService.cs:line 444
```

it seems that according to https://anansi-project.github.io/docs/comicinfo/schemas/v2.1 it should be ComicInfo not ComicInfoXml for the root tag it's generating in the xml as currently it's failing to validate against the xsd

**Comment by 9-FS** [comment]
I feel your pain. Komga is unbearably slow for me too and I'm also considering to switch first party support to something else. Can you recommend Kavita?

Thanks for reporting the issue. Problem is fixed and currently on `dev`. Will be merged into `main` and released as version 3.5.1. as soon as Komga decides to display a test hentai with the new ComicInfo.xml so I finally have confirmation that my fix does not break anything.

**Comment by ziweiwai** [comment]
Thanks for fixing - I think I'd have to redownload my collection first before I can report on whether kavita works any better. At the very least i'd have to figure something with the directory structure, i think it wants 1 folder per series/oneshot with the single cbz inside.

**Comment by 9-FS** [comment]
You can do that now properly with `LIBRARY_SPLIT = 1` in version 3.6.2.
